stages:

  download:
    cmd: protx data download
      --url ${data_dirs.uniref50_url}
      --output ${data_dirs.uniref50_fasta_gz}
    deps:
      - src/protx/data/downloader.py
    params:
      - data_dirs.uniref50_url
      - data_dirs.uniref50_fasta_gz
    outs:
      - ${data_dirs.uniref50_fasta_gz}

  extract:
    cmd: protx data extract
      --input ${data_dirs.uniref50_fasta_gz}
      --output ${data_dirs.uniref50_fasta}
    deps:
      - src/protx/data/extractor.py
      - ${data_dirs.uniref50_fasta_gz}
    params:
      - data_dirs.uniref50_fasta_gz
      - data_dirs.uniref50_fasta
    outs:
      - ${data_dirs.uniref50_fasta}

  shuffle_fasta:
    cmd: protx data shuffle
      --input ${data_dirs.uniref50_fasta}
      --output ${data_dirs.shuffled_fasta_file}
      --seed ${data_params.shuffle_seed}
    deps:
      - src/protx/data/shuffler.py
      - ${data_dirs.uniref50_fasta}
    params:
      - data_dirs.shuffled_fasta_file
      - data_params.shuffle_seed
    outs:
      - ${data_dirs.shuffled_fasta_file}

  filter_split:
    cmd: protx data filter-split
      --input ${data_dirs.shuffled_fasta_file}
      --filtered-seqs ${data_dirs.uniref50_filtered_fasta}
      --train-file ${data_dirs.train_fasta}
      --val-file ${data_dirs.val_fasta}
      --min-seq-len ${data_params.min_seq_len}
      --max-seq-len ${data_params.max_seq_len}
      --max-seqs-num ${data_params.max_seqs_num}
      --val-ratio ${data_params.val_ratio}
      --info-file ${data_dirs.info_file}
      --skip-n ${data_params.filter_skip_n}
    deps:
      - src/protx/data/filter_splitor.py
      - ${data_dirs.shuffled_fasta_file}
    params:
      - data_dirs.shuffled_fasta_file
      - data_dirs.uniref50_filtered_fasta
      - data_dirs.info_file
      - data_params.min_seq_len
      - data_params.max_seq_len
      - data_params.max_seqs_num
      - data_params.val_ratio
      - data_params.filter_skip_n
    outs:
      - ${data_dirs.uniref50_filtered_fasta}
      - ${data_dirs.train_fasta}
      - ${data_dirs.val_fasta}
      - ${data_dirs.info_file}
  
  save_protx_train_dataset:
    cmd: protx data save-dataset
      --input-file ${data_dirs.train_fasta}
      --teacher-model 'prott5'
      --output-file ${data_dirs.protx_train_prefix}
      --max-seq-len ${data_params.max_seq_len}
      --batch-size ${data_params.embed_calc_batch_size}
      --device 'auto'
      --n-files ${data_params.train_shards}
    deps:
      - src/protx/data/dataset.py
      - ${data_dirs.train_fasta}
    params:
      - data_dirs.train_fasta
      - data_dirs.protx_train_prefix
      - data_params.embed_calc_batch_size
      - data_params.train_shards

  save_protx_val_dataset:
    cmd: protx data save-dataset
      --input-file ${data_dirs.val_fasta}
      --teacher-model 'prott5'
      --output-file ${data_dirs.protx_val_prefix}
      --max-seq-len ${data_params.max_seq_len}
      --batch-size ${data_params.embed_calc_batch_size}
      --device 'auto'
      --n-files ${data_params.val_shards}
    deps:
      - src/protx/data/dataset.py
      - ${data_dirs.val_fasta}
    params:
      - data_dirs.protx_dataset_dir
      - data_dirs.protx_val_prefix
      - data_params.embed_calc_batch_size
      - data_params.val_shards
