data_params:
  val_ratio: 0.1
  max_seqs_num: 100
  min_seq_len: 20
  max_seq_len: 512
  embed_calc_batch_size: 64
  
  shuffle: true
  shuffle_seed: 23
  # If you want to skip some sequences
  filter_skip_n: 0
  # For sharding the train and val datasets
  train_shards: 5
  val_shards: 2

### DO NOT CHANGE CONFIGS BELOW ###
data_dirs:
  base_dir: "output/data"
  raw_dir: "output/data/raw"
  filter_split_dir: "output/data/filter_split"
  protx_dataset_dir: "output/data/protx_dataset"

  uniref50_url: "https://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref50/uniref50.fasta.gz" 
  uniref50_fasta_gz: "output/data/raw/uniref50.fasta.gz"
  uniref50_fasta: "output/data/raw/uniref50.fasta"

  shuffled_fasta_file: "output/data/raw/uniref50_shuffled.fasta"

  uniref50_filtered_fasta: "output/data/filter_split/uniref50_filtered.fasta"
  train_fasta: "output/data/filter_split/train.fasta"
  val_fasta: "output/data/filter_split/val.fasta"
  info_file: "output/data/filter_split/dataset_info.txt"

  protx_train_prefix: "output/data/protx_dataset/train/train.h5"
  protx_val_prefix: "output/data/protx_dataset/val/val.h5"

  wandb_checkpoints_dir: "output/wandb_checkpoints"